spring.application.name=atlas_ecomm
server.port=8090

# MongoDB Atlas connection
 spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.xyz.mongodb.net/my_ecom_db

# spring.data.mongodb.database=my_ecom_db
#spring.data.mongodb.repositories.enabled=true



